name: Build

on:
  push:
    tags:
      - "*"

env:
  SCED_TAG: ${{ vars.SCED_TAG }}
  TTS_MOD_MANAGER_VERSION: ${{ vars.TTS_MOD_MANAGER_VERSION }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: make init
      - run: make build
      - uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          files: |
            .build/*
            downloadable/**/*.json
            library.json
            modversion.json
          make_latest: true
          fail_on_unmatched_files: true
          generate_release_notes: true
